import json
import re

with open('scripts/config.json', 'r', encoding = 'utf-8') as file:
    CONFIG = json.load(file)

INPUTS = CONFIG['inputs']
OUTPUTS = CONFIG['outputs']

# Lists
ALL_POKEMON = [
    'SPECIES_BULBASAUR',
    'SPECIES_CHARMANDER',
    'SPECIES_SQUIRTLE',
    'SPECIES_CATERPIE',
    'SPECIES_WEEDLE',
    'SPECIES_PIDGEY',
    'SPECIES_RATTATA',
    'SPECIES_SPEAROW',
    'SPECIES_EKANS',
    'SPECIES_SANDSHREW',
    'SPECIES_NIDORAN_F',
    'SPECIES_NIDORAN_M',
    'SPECIES_VULPIX',
    'SPECIES_ZUBAT',
    'SPECIES_ODDISH',
    'SPECIES_PARAS',
    'SPECIES_VENONAT',
    'SPECIES_DIGLETT',
    'SPECIES_MEOWTH',
    'SPECIES_PSYDUCK',
    'SPECIES_MANKEY',
    'SPECIES_GROWLITHE',
    'SPECIES_POLIWAG',
    'SPECIES_ABRA',
    'SPECIES_MACHOP',
    'SPECIES_BELLSPROUT',
    'SPECIES_TENTACOOL',
    'SPECIES_GEODUDE',
    'SPECIES_PONYTA',
    'SPECIES_SLOWPOKE',
    'SPECIES_MAGNEMITE',
    'SPECIES_DODUO',
    'SPECIES_SEEL',
    'SPECIES_GRIMER',
    'SPECIES_SHELLDER',
    'SPECIES_GASTLY',
    'SPECIES_ONIX',
    'SPECIES_DROWZEE',
    'SPECIES_KRABBY',
    'SPECIES_VOLTORB',
    'SPECIES_EXEGGCUTE',
    'SPECIES_CUBONE',
    'SPECIES_LICKITUNG',
    'SPECIES_KOFFING',
    'SPECIES_RHYHORN',
    'SPECIES_TANGELA',
    'SPECIES_HORSEA',
    'SPECIES_GOLDEEN',
    'SPECIES_STARYU',
    'SPECIES_SCYTHER',
    'SPECIES_MAGIKARP',
    'SPECIES_EEVEE',
    'SPECIES_PORYGON',
    'SPECIES_OMANYTE',
    'SPECIES_KABUTO',
    'SPECIES_DRATINI',
    'SPECIES_CHIKORITA',
    'SPECIES_CYNDAQUIL',
    'SPECIES_TOTODILE',
    'SPECIES_SENTRET',
    'SPECIES_HOOTHOOT',
    'SPECIES_LEDYBA',
    'SPECIES_SPINARAK',
    'SPECIES_CHINCHOU',
    'SPECIES_PICHU',
    'SPECIES_CLEFFA',
    'SPECIES_IGGLYBUFF',
    'SPECIES_TOGEPI',
    'SPECIES_NATU',
    'SPECIES_MAREEP',
    'SPECIES_HOPPIP',
    'SPECIES_AIPOM',
    'SPECIES_SUNKERN',
    'SPECIES_YANMA',
    'SPECIES_WOOPER',
    'SPECIES_WOOPER_PALDEA',
    'SPECIES_MURKROW',
    'SPECIES_MISDREAVUS',
    'SPECIES_GIRAFARIG',
    'SPECIES_FARFETCHD_GALAR',
    'SPECIES_PINECO',
    'SPECIES_DUNSPARCE',
    'SPECIES_GLIGAR',
    'SPECIES_SNUBBULL',
    'SPECIES_SNEASEL',
    'SPECIES_TEDDIURSA',
    'SPECIES_SLUGMA',
    'SPECIES_SWINUB',
    'SPECIES_HOUNDOUR',
    'SPECIES_PHANPY',
    'SPECIES_TYROGUE',
    'SPECIES_SMOOCHUM',
    'SPECIES_ELEKID',
    'SPECIES_MAGBY',
    'SPECIES_LARVITAR',
    'SPECIES_TREECKO',
    'SPECIES_TORCHIC',
    'SPECIES_MUDKIP',
    'SPECIES_POOCHYENA',
    'SPECIES_ZIGZAGOON',
    'SPECIES_WURMPLE',
    'SPECIES_LOTAD',
    'SPECIES_SEEDOT',
    'SPECIES_TAILLOW',
    'SPECIES_WINGULL',
    'SPECIES_RALTS',
    'SPECIES_SURSKIT',
    'SPECIES_SHROOMISH',
    'SPECIES_SLAKOTH',
    'SPECIES_NINCADA',
    'SPECIES_WHISMUR',
    'SPECIES_MAKUHITA',
    'SPECIES_AZURILL',
    'SPECIES_NOSEPASS',
    'SPECIES_SKITTY',
    'SPECIES_ARON',
    'SPECIES_MEDITITE',
    'SPECIES_ELECTRIKE',
    'SPECIES_GULPIN',
    'SPECIES_CARVANHA',
    'SPECIES_WAILMER',
    'SPECIES_NUMEL',
    'SPECIES_SPOINK',
    'SPECIES_TRAPINCH',
    'SPECIES_CACNEA',
    'SPECIES_SWABLU',
    'SPECIES_BARBOACH',
    'SPECIES_CORPHISH',
    'SPECIES_BALTOY',
    'SPECIES_LILEEP',
    'SPECIES_ANORITH',
    'SPECIES_FEEBAS',
    'SPECIES_SHUPPET',
    'SPECIES_DUSKULL',
    'SPECIES_WYNAUT',
    'SPECIES_SNORUNT',
    'SPECIES_SPHEAL',
    'SPECIES_CLAMPERL',
    'SPECIES_BAGON',
    'SPECIES_TURTWIG',
    'SPECIES_CHIMCHAR',
    'SPECIES_PIPLUP',
    'SPECIES_STARLY',
    'SPECIES_BIDOOF',
    'SPECIES_KRICKETOT',
    'SPECIES_SHINX',
    'SPECIES_BUDEW',
    'SPECIES_CRANIDOS',
    'SPECIES_SHIELDON',
    'SPECIES_BURMY_PLANT',
    'SPECIES_COMBEE',
    'SPECIES_BUIZEL',
    'SPECIES_CHERUBI',
    'SPECIES_SHELLOS_EAST',
    'SPECIES_DRIFLOON',
    'SPECIES_BUNEARY',
    'SPECIES_GLAMEOW',
    'SPECIES_CHINGLING',
    'SPECIES_STUNKY',
    'SPECIES_BRONZOR',
    'SPECIES_BONSLY',
    'SPECIES_MIME_JR',
    'SPECIES_HAPPINY',
    'SPECIES_GIBLE',
    'SPECIES_MUNCHLAX',
    'SPECIES_RIOLU',
    'SPECIES_HIPPOPOTAS',
    'SPECIES_SKORUPI',
    'SPECIES_CROAGUNK',
    'SPECIES_FINNEON',
    'SPECIES_MANTYKE',
    'SPECIES_SNOVER',
    'SPECIES_SNIVY',
    'SPECIES_TEPIG',
    'SPECIES_OSHAWOTT',
    'SPECIES_PATRAT',
    'SPECIES_LILLIPUP',
    'SPECIES_PURRLOIN',
    'SPECIES_PANSAGE',
    'SPECIES_PANSEAR',
    'SPECIES_PANPOUR',
    'SPECIES_MUNNA',
    'SPECIES_PIDOVE',
    'SPECIES_BLITZLE',
    'SPECIES_ROGGENROLA',
    'SPECIES_WOOBAT',
    'SPECIES_DRILBUR',
    'SPECIES_TIMBURR',
    'SPECIES_TYMPOLE',
    'SPECIES_SEWADDLE',
    'SPECIES_VENIPEDE',
    'SPECIES_COTTONEE',
    'SPECIES_PETILIL',
    'SPECIES_SANDILE',
    'SPECIES_DARUMAKA',
    'SPECIES_DWEBBLE',
    'SPECIES_SCRAGGY',
    'SPECIES_YAMASK',
    'SPECIES_TIRTOUGA',
    'SPECIES_ARCHEN',
    'SPECIES_TRUBBISH',
    'SPECIES_ZORUA',
    'SPECIES_GOTHITA',
    'SPECIES_SOLOSIS',
    'SPECIES_DUCKLETT',
    'SPECIES_VANILLITE',
    'SPECIES_DEERLING_SPRING',
    'SPECIES_KARRABLAST',
    'SPECIES_FOONGUS',
    'SPECIES_FRILLISH',
    'SPECIES_JOLTIK',
    'SPECIES_FERROSEED',
    'SPECIES_KLINK',
    'SPECIES_TYNAMO',
    'SPECIES_ELGYEM',
    'SPECIES_LITWICK',
    'SPECIES_AXEW',
    'SPECIES_CUBCHOO',
    'SPECIES_SHELMET',
    'SPECIES_MIENFOO',
    'SPECIES_GOLETT',
    'SPECIES_PAWNIARD',
    'SPECIES_RUFFLET',
    'SPECIES_VULLABY',
    'SPECIES_DEINO',
    'SPECIES_LARVESTA',
    'SPECIES_CHESPIN',
    'SPECIES_FENNEKIN',
    'SPECIES_FROAKIE',
    'SPECIES_BUNNELBY',
    'SPECIES_FLETCHLING',
    'SPECIES_SCATTERBUG_TEMPLATE',
    'SPECIES_LITLEO',
    'SPECIES_FLABEBE_TEMPLATE',
    'SPECIES_SKIDDO',
    'SPECIES_PANCHAM',
    'SPECIES_ESPURR',
    'SPECIES_HONEDGE',
    'SPECIES_SPRITZEE',
    'SPECIES_SWIRLIX',
    'SPECIES_INKAY',
    'SPECIES_BINACLE',
    'SPECIES_SKRELP',
    'SPECIES_CLAUNCHER',
    'SPECIES_HELIOPTILE',
    'SPECIES_TYRUNT',
    'SPECIES_AMAURA',
    'SPECIES_GOOMY',
    'SPECIES_PHANTUMP',
    'SPECIES_PUMPKABOO_SUPER',
    'SPECIES_BERGMITE',
    'SPECIES_NOIBAT',
    'SPECIES_ROWLET',
    'SPECIES_LITTEN',
    'SPECIES_POPPLIO',
    'SPECIES_PIKIPEK',
    'SPECIES_YUNGOOS',
    'SPECIES_GRUBBIN',
    'SPECIES_CRABRAWLER',
    'SPECIES_CUTIEFLY',
    'SPECIES_ROCKRUFF',
    'SPECIES_MAREANIE',
    'SPECIES_MUDBRAY',
    'SPECIES_DEWPIDER',
    'SPECIES_FOMANTIS',
    'SPECIES_MORELULL',
    'SPECIES_SALANDIT',
    'SPECIES_STUFFUL',
    'SPECIES_BOUNSWEET',
    'SPECIES_WIMPOD',
    'SPECIES_SANDYGAST',
    'SPECIES_TYPE_NULL',
    'SPECIES_JANGMO_O',
    'SPECIES_POIPOLE',
    'SPECIES_MELTAN',
    'SPECIES_GROOKEY',
    'SPECIES_SCORBUNNY',
    'SPECIES_SOBBLE',
    'SPECIES_SKWOVET',
    'SPECIES_ROOKIDEE',
    'SPECIES_BLIPBUG',
    'SPECIES_NICKIT',
    'SPECIES_GOSSIFLEUR',
    'SPECIES_WOOLOO',
    'SPECIES_CHEWTLE',
    'SPECIES_YAMPER',
    'SPECIES_ROLYCOLY',
    'SPECIES_APPLIN',
    'SPECIES_SILICOBRA',
    'SPECIES_ARROKUDA',
    'SPECIES_TOXEL',
    'SPECIES_SIZZLIPEDE',
    'SPECIES_CLOBBOPUS',
    'SPECIES_SINISTEA_ANTIQUE',
    'SPECIES_IMPIDIMP',
    'SPECIES_MILCERY',
    'SPECIES_SNOM',
    'SPECIES_CUFANT',
    'SPECIES_DURALUDON',
    'SPECIES_DREEPY',
    'SPECIES_KUBFU',
    'SPECIES_RATTATA_ALOLA',
    'SPECIES_SANDSHREW_ALOLA',
    'SPECIES_VULPIX_ALOLA',
    'SPECIES_DIGLETT_ALOLA',
    'SPECIES_MEOWTH_ALOLA',
    'SPECIES_GEODUDE_ALOLA',
    'SPECIES_GRIMER_ALOLA',
    'SPECIES_MEOWTH_GALAR',
    'SPECIES_PONYTA_GALAR',
    'SPECIES_SLOWPOKE_GALAR',
    'SPECIES_CORSOLA_GALAR',
    'SPECIES_ZIGZAGOON_GALAR',
    'SPECIES_DARUMAKA_GALAR',
    'SPECIES_YAMASK_GALAR',
    'SPECIES_GROWLITHE_HISUI',
    'SPECIES_VOLTORB_HISUI',
    'SPECIES_QWILFISH_HISUI',
    'SPECIES_SNEASEL_HISUI',
    'SPECIES_ZORUA_HISUI',
    'SPECIES_PICHU_SPIKY_EARED',
    'SPECIES_BURMY_SANDY',
    'SPECIES_BURMY_TRASH',
    'SPECIES_BASCULIN_WHITE_STRIPED',
    'SPECIES_DEERLING_SUMMER',
    'SPECIES_DEERLING_AUTUMN',
    'SPECIES_DEERLING_WINTER',
    'SPECIES_SPRIGATITO',
    'SPECIES_FUECOCO',
    'SPECIES_QUAXLY',
    'SPECIES_LECHONK',
    'SPECIES_TAROUNTULA',
    'SPECIES_NYMBLE',
    'SPECIES_TANDEMAUS',
    'SPECIES_FIDOUGH',
    'SPECIES_SMOLIV',
    'SPECIES_NACLI',
    'SPECIES_CHARCADET',
    'SPECIES_TADBULB',
    'SPECIES_WATTREL',
    'SPECIES_MASCHIFF',
    'SPECIES_SHROODLE',
    'SPECIES_BRAMBLIN',
    'SPECIES_TOEDSCOOL',
    'SPECIES_CAPSAKID',
    'SPECIES_RELLOR',
    'SPECIES_FLITTLE',
    'SPECIES_TINKATINK',
    'SPECIES_WIGLETT',
    'SPECIES_FINIZEN',
    'SPECIES_VAROOM',
    'SPECIES_GLIMMET',
    'SPECIES_GREAVARD',
    'SPECIES_CETODDLE',
    'SPECIES_FRIGIBAX',
    'SPECIES_GIMMIGHOUL_CHEST',
    'SPECIES_GIMMIGHOUL_ROAMING',
    'SPECIES_POLTCHAGEIST_COUNTERFEIT',
    'SPECIES_PICHU_MEGA',
    'SPECIES_CLEFFA_MEGA',
    'SPECIES_IGGLYBUFF_MEGA',
    'SPECIES_TOGEPI_MEGA',
    'SPECIES_TYROGUE_MEGA_L',
    'SPECIES_TYROGUE_MEGA_C',
    'SPECIES_TYROGUE_MEGA_T',
    'SPECIES_SMOOCHUM_MEGA',
    'SPECIES_ELEKID_MEGA',
    'SPECIES_MAGBY_MEGA',
    'SPECIES_AZURILL_MEGA',
    'SPECIES_WYNAUT_MEGA',
    'SPECIES_BUDEW_MEGA',
    'SPECIES_CHINGLING_MEGA',
    'SPECIES_BONSLY_MEGA',
    'SPECIES_MIME_JR_MEGA_K',
    'SPECIES_HAPPINY_MEGA',
    'SPECIES_MUNCHLAX_MEGA',
    'SPECIES_RIOLU_MEGA',
    'SPECIES_MANTYKE_MEGA',
    'SPECIES_TOXEL_MEGA_A',
    'SPECIES_TOXEL_MEGA_L',
    'SPECIES_EEVEE_FIRE',
    'SPECIES_EEVEE_WATER',
    'SPECIES_EEVEE_ELECTRIC',
    'SPECIES_EEVEE_DARK',
    'SPECIES_EEVEE_PSYCHIC',
    'SPECIES_EEVEE_GRASS',
    'SPECIES_EEVEE_ICE',
    'SPECIES_EEVEE_FAIRY',
    'SPECIES_CHARCADET_PSYCHIC',
    'SPECIES_CHARCADET_GHOST',
    'SPECIES_RALTS_FIGHTING',
    'SPECIES_SNORUNT_GHOST',
    'SPECIES_WURMPLE_POISON',
    'SPECIES_NINCADA_GHOST',
    'SPECIES_EXEGGCUTE_DRAGON',
    'SPECIES_KOFFING_FAIRY',
    'SPECIES_PETILIL_FIGHTING',
    'SPECIES_RUFFLET_PSYCHIC',
    'SPECIES_GOOMY_STEEL',
    'SPECIES_BERGMITE_ROCK',
    'SPECIES_MIME_JR_MEGA_G',
    'SPECIES_MAGIKARP_MONSTER',
    'SPECIES_FROAKIE_SPECIAL',
    'SPECIES_ROCKRUFF_SPECIAL',
    'SPECIES_FEEBAS_FAIRY',
    'SPECIES_STARYU_SPECIAL',
    'SPECIES_TEDDIURSA_BLOODMOON',
    'SPECIES_REMORAID',
    'SPECIES_BELDUM',
    'SPECIES_MINCCINO',
    'SPECIES_PAWMI',
    'SPECIES_HATENNA',
    'SPECIES_STANTLER',
    'SPECIES_COSMOG',
    
]

ALL_TMHMS = [
    'MOVE_WORK_UP',
    'MOVE_DRAGON_CLAW',
    'MOVE_WATER_PULSE',
    'MOVE_CALM_MIND',
    'MOVE_PSYSHOCK',
    'MOVE_TOXIC',
    'MOVE_SNOWSCAPE',
    'MOVE_BULK_UP',
    'MOVE_BULLET_SEED',
    'MOVE_HIDDEN_POWER',
    'MOVE_SUNNY_DAY',
    'MOVE_TAUNT',
    'MOVE_ICE_BEAM',
    'MOVE_BLIZZARD',
    'MOVE_HYPER_BEAM',
    'MOVE_LIGHT_SCREEN',
    'MOVE_PROTECT',
    'MOVE_RAIN_DANCE',
    'MOVE_GIGA_DRAIN',
    'MOVE_ROOST',
    'MOVE_POWER_GEM',
    'MOVE_SOLAR_BEAM',
    'MOVE_IRON_TAIL',
    'MOVE_THUNDERBOLT',
    'MOVE_THUNDER',
    'MOVE_EARTHQUAKE',
    'MOVE_RETURN',
    'MOVE_DIG',
    'MOVE_PSYCHIC',
    'MOVE_SHADOW_BALL',
    'MOVE_BRICK_BREAK',
    'MOVE_LEECH_LIFE',
    'MOVE_REFLECT',
    'MOVE_SHOCK_WAVE',
    'MOVE_FLAMETHROWER',
    'MOVE_SLUDGE_BOMB',
    'MOVE_SANDSTORM',
    'MOVE_FIRE_BLAST',
    'MOVE_ROCK_TOMB',
    'MOVE_AERIAL_ACE',
    'MOVE_EARTH_POWER',
    'MOVE_FACADE',
    'MOVE_SECRET_POWER',
    'MOVE_REST',
    'MOVE_ATTRACT',
    'MOVE_THIEF',
    'MOVE_STEEL_WING',
    'MOVE_SKILL_SWAP',
    'MOVE_LOW_SWEEP',
    'MOVE_OVERHEAT',
    'MOVE_SCALD',
    'MOVE_AGILITY',
    'MOVE_FIRE_FANG',
    'MOVE_THUNDER_FANG',
    'MOVE_ICE_FANG',
    'MOVE_PSYCHIC_FANGS',
    'MOVE_FIRE_PUNCH',
    'MOVE_THUNDER_PUNCH',
    'MOVE_ICE_PUNCH',
    'MOVE_EXPANDING_FORCE',
    'MOVE_ACROBATICS',
    'MOVE_MIRROR_SHOT',
    'MOVE_FLAME_CHARGE',
    'MOVE_TRAILBLAZE',
    'MOVE_POUNCE',
    'MOVE_CHILLING_WATER',
    'MOVE_STEALTH_ROCK',
    'MOVE_BULLDOZE',
    'MOVE_GUNK_SHOT',
    'MOVE_ICE_SPINNER',
    'MOVE_LIQUIDATION',
    'MOVE_SCALE_SHOT',
    'MOVE_METAL_CLAW',
    'MOVE_ICY_WIND',
    'MOVE_DRAINING_KISS',
    'MOVE_AIR_CUTTER',
    'MOVE_AIR_SLASH',
    'MOVE_STORED_POWER',
    'MOVE_AVALANCHE',
    'MOVE_VOLT_SWITCH',
    'MOVE_FLING',
    'MOVE_IRON_HEAD',
    'MOVE_ZEN_HEADBUTT',
    'MOVE_SHADOW_CLAW',
    'MOVE_FOUL_PLAY',
    'MOVE_BODY_SLAM',
    'MOVE_SLEEP_TALK',
    'MOVE_LASH_OUT',
    'MOVE_HYPER_VOICE',
    'MOVE_SEED_BOMB',
    'MOVE_DRAIN_PUNCH',
    'MOVE_DAZZLING_GLEAM',
    'MOVE_PLAY_ROUGH',
    'MOVE_POISON_JAB',
    'MOVE_THUNDER_WAVE',
    'MOVE_ROCK_SLIDE',
    'MOVE_SWORDS_DANCE',
    'MOVE_U_TURN',
    'MOVE_FLASH_CANNON',
    'MOVE_DARK_PULSE',
    'MOVE_CUT',
    'MOVE_FLY',
    'MOVE_SURF',
    'MOVE_STRENGTH',
    'MOVE_FLASH',
    'MOVE_ROCK_SMASH',
    'MOVE_WATERFALL',
    'MOVE_DIVE',
]

ALL_TUTORS = [
    'MOVE_DYNAMIC_PUNCH',
    'MOVE_DOUBLE_EDGE',
    'MOVE_EXPLOSION',
    'MOVE_FURY_CUTTER',
    'MOVE_METRONOME',
    'MOVE_MIMIC',
    'MOVE_ROLLOUT',
    'MOVE_SLEEP_TALK',
    'MOVE_SUBSTITUTE',
    'MOVE_SWAGGER',
    'MOVE_SHELL_SMASH',
    'MOVE_CRUNCH',
    'MOVE_AQUA_TAIL',
    'MOVE_HEAVY_SLAM',
    'MOVE_HEAT_WAVE',
    'MOVE_ENERGY_BALL',
    'MOVE_HIGH_HORSEPOWER',
    'MOVE_THROAT_CHOP',
    'MOVE_JUMP_KICK',
    'MOVE_LUNGE',
    'MOVE_DRAGON_PULSE',
    'MOVE_MUDDY_WATER',
    'MOVE_HAMMER_ARM',
    'MOVE_SCORCHING_SANDS',
    'MOVE_DRILL_RUN',
    'MOVE_RISING_VOLTAGE',
    'MOVE_CLOSE_COMBAT',
    'MOVE_WILD_CHARGE',
    'MOVE_FLARE_BLITZ',
    'MOVE_HYDRO_PUMP',
    'MOVE_DRAGON_RUSH',
    'MOVE_FOCUS_BLAST',
    'MOVE_LEAF_STORM',
    'MOVE_THRASH',
    'MOVE_OUTRAGE',
    'MOVE_BOOMBURST',
    'MOVE_HURRICANE',
    'MOVE_STONE_EDGE',
    'MOVE_POWER_WHIP',
    'MOVE_RAGING_FURY',
    'MOVE_PSYCHO_BOOST',
    'MOVE_HIGH_JUMP_KICK',
    'MOVE_DRACO_METEOR',
    'MOVE_MEGAHORN',
    'MOVE_HEAD_SMASH',
    'MOVE_SUPERPOWER',
    'MOVE_SOLAR_BLADE',
    'MOVE_SKY_ATTACK',
    'MOVE_METEOR_BEAM',
    'MOVE_REVIVAL_BLESSING',
    'MOVE_VOLT_TACKLE',
    'MOVE_PLASMA_FISTS',
    'MOVE_BOUNCY_BUBBLE',
    'MOVE_SIZZLY_SLIDE',
    'MOVE_ZAPPY_ZAP',
    'MOVE_GLITZY_GLOW',
    'MOVE_BADDY_BAD',
    'MOVE_FREEZY_FROST',
    'MOVE_SAPPY_SEED',
    'MOVE_SPARKLY_SWIRL',
]

# Mappings
SPECIAL_NAMES = {
    'SPECIES_NIDORAN_M'                 : 'Nidoran♂',
    'SPECIES_NIDORAN_F'                 : 'Nidoran♀',
    'SPECIES_BURMY_PLANT'               : 'Burmy-Plant',
    'SPECIES_BURMAY_SANDY'              : 'Burmy-Sandy',
    'SPECIES_MIME_JR'                   : 'Mime Jr.',
    'SPECIES_DEERLING_SPRING'           : 'Deerling-Spring',
    'SPECIES_DEERLING_SUMMER'           : 'Deerling-Summer',
    'SPECIES_DEERLING_AUTUMN'           : 'Deerling-Autumn',
    'SPECIES_DEERLING_WINTER'           : 'Deerling-Winter',
    'SPECIES_TYPE_NULL'                 : 'Type: Null',
    'SPECIES_JANGMO_O'                  : 'Jangmo-o',
    'SPECIES_BASCULIN_WHITE_STRIPED'    : 'Basculin-White',
    'SPECIES_GIMMIGHOUL_CHEST'          : 'Gimmighoul-Chest',
    'SPECIES_GIMMIGHOUL_ROAMING'        : 'Gimmighoul-Roaming',
    'SPECIES_EEVEE_FIRE'                : 'Eevee-Fire',
    'SPECIES_EEVEE_WATER'               : 'Eevee-Water',
    'SPECIES_EEVEE_ELECTRIC'            : 'Eevee-Electric',
    'SPECIES_EEVEE_DARK'                : 'Eevee-Dark',
    'SPECIES_EEVEE_PSYCHIC'             : 'Eevee-Psychic',
    'SPECIES_EEVEE_GRASS'               : 'Eevee-Grass',
    'SPECIES_EEVEE_ICE'                 : 'Eevee-Ice',
    'SPECIES_EEVEE_FAIRY'               : 'Eevee-Fairy',
    'SPECIES_CHARCADET_PSYCHIC'         : 'Charcadet-Psychic',
    'SPECIES_CHARCADET_GHOST'           : 'Charcadet-Ghost',
    'SPECIES_RALTS_FIGHTING'            : 'Ralts-Fighting',
    'SPECIES_SNORUNT_GHOST'             : 'Snorunt-Ghost',
    'SPECIES_WURMPLE_POISON'            : 'Wurmple-Poison',
    'SPECIES_NINCADA_GHOST'             : 'Nincada-Ghost',
    'SPECIES_EXEGGCUTE_DRAGON'          : 'Exeggcute-Alola',
    'SPECIES_KOFFING_FAIRY'             : 'Koffing-Galar',
    'SPECIES_PETILIL_FIGHTING'          : 'Petilil-Hisui',
    'SPECIES_RUFFLET_PSYCHIC'           : 'Rufflet-Hisui',
    'SPECIES_GOOMY_STEEL'               : 'Goomy-Hisui',
    'SPECIES_BERGMITE_ROCK'             : 'Bergmite-Hisui',
    'SPECIES_MAGIKARP_MONSTER'          : 'Magikarp-Monster',
    'SPECIES_FROAKIE_SPECIAL'           : 'Froakie-Special',
    'SPECIES_STARYU_SPECIAL'            : 'Staryu-Special',
    'SPECIES_ROCKRUFF_SPECIAL'          : 'Rockruff-Special',
    'SPECIES_FEEBAS_FAIRY'              : 'Feebas-Fairy',
    'SPECIES_TEDDIURSA_BLOODMOON'       : 'Teddiursa-Bloodmoon',
}

SPRITE_SPECIAL_CASES = {
    'nidoran-f'                 : 'nidoran_f',
    'nidoran-m'                 : 'nidoran_m',
    'shellos-east'              : 'shellos',
    'mime-jr'                   : 'mime_jr',
    'pumpkaboo-super'           : 'pumpkaboo',
    'type-null'                 : 'type_null',
    'jangmo-o'                  : 'jangmo_o',
    'pichu-spiky-eared'         : 'pichu',
    'basculin-white-striped'    : 'basculin-white_striped',
}

TARGET_MAPPING = {
    'MOVE_TARGET_SELECTED'      : 'An Adjacent Pokémon',
    'MOVE_TARGET_BOTH'          : 'Both Foes',
    'MOVE_TARGET_USER'          : 'The User',
    'MOVE_TARGET_FOES_AND_ALLY' : 'All Adjacent Pokémon',
    'MOVE_TARGET_DEPENDS'       : 'Special',
    'MOVE_TARGET_RANDOM'        : 'Random',
    'MOVE_TARGET_ALL_BATTLERS'  : 'The Field',
}

MOVE_EFFECT_MAPPING = {
    'MOVE_EFFECT_PARALYSIS'                     : 'Paralyze',
    'MOVE_EFFECT_POISON'                        : 'Poison',
    'MOVE_EFFECT_BURN'                          : 'Burn',
    'MOVE_EFFECT_SLEEP'                         : 'Sleep',
    'MOVE_EFFECT_CONFUSION'                     : 'Confuse',
    'MOVE_EFFECT_FREEZE_OR_FROSTBITE'           : 'Freeze',
    'MOVE_EFFECT_FLINCH'                        : 'Flinch',
    'MOVE_EFFECT_LEECH_SEED'                    : 'Leech Seed',
    'MOVE_EFFECT_TRI_ATTACK'                    : 'Paralyze, Burn, or Freeze',
    'MOVE_EFFECT_ALL_STATS_UP'                  : 'Raise All Stats 1 Stage',
    'MOVE_EFFECT_SECRET_POWER'                  : 'Paralyze, Drop Accuracy 1 Stage, Flinch, Confuse, Poison, Sleep, Drop Speed 1 Stage, Drop Attack 1 Stage, Drop Defense 1 Stage',
    'MOVE_EFFECT_TOXIC'                         : 'Badly Poison',
    'MOVE_EFFECT_PREVENT_ESCAPE'                : 'Prevent Escape',
    'MOVE_EFFECT_REMOVE_STATUS'                 : 'Cure Status Conditions',
    'MOVE_EFFECT_THROAT_CHOP'                   : 'Disable Sound Moves',
    'MOVE_EFFECT_ION_DELUGE'                    : 'Turn Normal Moves Electric',
    'MOVE_EFFECT_LIGHT_SCREEN'                  : 'Set Up Light Screen',
    'MOVE_EFFECT_REFLECT'                       : 'Set Up Reflect',
    'MOVE_EFFECT_PREVENT_HAZE'                  : 'Clear Stat Changes',
    'MOVE_EFFECT_EERIE_SPELL'                   : 'Cut 3 PP',
    'MOVE_EFFECT_DIRE_CLAW'                     : 'Poison, Sleep, or Paralyze',
    'MOVE_EFFECT_STEALTH_ROCK'                  : 'Set Up Stealth Rock',
    'MOVE_EFFECT_SPIKES'                        : 'Set Up a Layer of Spikes',
    'MOVE_EFFECT_SALT_CURE'                     : 'Damages Every Turn',
    'MOVE_EFFECT_SYRUP_BOMB'                    : 'Drops Speed Each Turn for 3 Turns',
    'MOVE_EFFECT_PSYCHIC_NOISE'                 : 'Disable Healing Moves',
}

STAT_MAPPING = {
    'ACC'       : 'Accuracy',
    'ATK'       : 'Attack',
    'DEF'       : 'Defense',
    'SP_ATK'    : 'Spacial Attack',
    'SP_DEF'    : 'Special Defense',
    'SPD'       : 'Speed',
    'EVS'       : 'EV Yield',
}

TM_NAMES = {
    'Tm Covet'                  : 'TM01 Covet',
    'Tm Dragon Claw'            : 'TM02 Dragon Claw',
    'Tm Water Pulse'            : 'TM03 Water Pulse',
    'Tm Calm Mind'              : 'TM04 Calm Mind',
    'Tm Psyshock'               : 'TM05 Psyshock',
    'Tm Toxic'                  : 'TM06 Toxic',
    'Tm Snowscape'              : 'TM07 Snowscape',
    'Tm Bulk Up'                : 'TM08 Bulk Up',
    'Tm Bullet Seed'            : 'TM09 Bullet Seed',
    'Tm Hidden Power'           : 'TM10 Hidden Power',
    'Tm Sunny Day'              : 'TM11 Sunny Day',
    'Tm Taunt'                  : 'TM12 Taunt',
    'Tm Ice Beam'               : 'TM13 Ice Beam',
    'Tm Blizzard'               : 'TM14 Blizzard',
    'Tm Hyper Beam'             : 'TM15 Hyper Beam',
    'Tm Light Screen'           : 'TM16 Light Screen',
    'Tm Protect'                : 'TM17 Protect',
    'Tm Rain Dance'             : 'TM18 Rain Dance',
    'Tm Giga Drain'             : 'TM19 Giga Drain',
    'Tm Roost'                  : 'TM20 Roost',
    'Tm Power Gem'              : 'TM21 Power Gem',
    'Tm Solar Beam'             : 'TM22 Solar Beam',
    'Tm Iron Tail'              : 'TM23 Iron Tail',
    'Tm Thunderbolt'            : 'TM24 Thunderbolt',
    'Tm Thunder'                : 'TM25 Thunder',
    'Tm Earthquake'             : 'TM26 Earthquake',
    'Tm Return'                 : 'TM27 Return',
    'Tm Dig'                    : 'TM28 Dig',
    'Tm Psychic'                : 'TM29 Psychic',
    'Tm Shadow Ball'            : 'TM30 Shadow Ball',
    'Tm Brick Break'            : 'TM31 Brick Break',
    'Tm Leech Life'             : 'TM32 Leech Life',
    'Tm Reflect'                : 'TM33 Reflect',
    'Tm Shock Wave'             : 'TM34 Shock Wave',
    'Tm Flamethrower'           : 'TM35 Flamethrower',
    'Tm Sludge Bomb'            : 'TM36 Sludge Bomb',
    'Tm Sandstorm'              : 'TM37 Sandstorm',
    'Tm Fire Blast'             : 'TM38 Fire Blast',
    'Tm Rock Tomb'              : 'TM39 Rock Tomb',
    'Tm Aerial Ace'             : 'TM40 Aerial Ace',
    'Tm Earth Power'            : 'TM41 Earth Power',
    'Tm Facade'                 : 'TM42 Facade',
    'Tm Secret Power'           : 'TM43 Secret Power',
    'Tm Rest'                   : 'TM44 Rest',
    'Tm Attract'                : 'TM45 Attract',
    'Tm Thief'                  : 'TM46 Thief',
    'Tm Steel Wing'             : 'TM47 Steel Wing',
    'Tm Skill Swap'             : 'TM48 Skill Swap',
    'Tm Low Sweep'              : 'TM49 Low Sweep',
    'Tm Overheat'               : 'TM50 Overheat',
    'Tm Scald'                  : 'TM51 Scald',
    'Tm Agility'                : 'TM52 Agility',
    'Tm Fire Fang'              : 'TM53 Fire Fang',
    'Tm Thunder Fang'           : 'TM54 Thunder Fang',
    'Tm Ice Fang'               : 'TM55 Ice Fang',
    'Tm Psychic Fangs'          : 'TM56 Psychic Fangs',
    'Tm Fire Punch'             : 'TM57 Fire Punch',
    'Tm Thunder Punch'          : 'TM58 Thunder Punch',
    'Tm Ice Punch'              : 'TM59 Ice Punch',
    'Tm Expanding Force'        : 'TM60 Expanding Force',
    'Tm Acrobatics'             : 'TM61 Acrobatics',
    'Tm Mirror Shot'            : 'TM62 Mirror Shot',
    'Tm Flame Charge'           : 'TM63 Flame Charge',
    'Tm Trailblaze'             : 'TM64 Trailblaze',
    'Tm Pounce'                 : 'TM65 Pounce',
    'Tm Chilling Water'         : 'TM66 Chilling Water',
    'Tm Stealth Rock'           : 'TM67 Stealth Rock',
    'Tm Bulldoze'               : 'TM68 Bulldoze',
    'Tm Gunk Shot'              : 'TM69 Gunk Shot',
    'Tm Ice Spinner'            : 'TM70 Ice Spinner',
    'Tm Liquidation'            : 'TM71 Liquidation',
    'Tm Scale Shot'             : 'TM72 Scale Shot',
    'Tm Metal Claw'             : 'TM73 Metal Claw',
    'Tm Icy Wind'               : 'TM74 Icy Wind',
    'Tm Draining Kiss'          : 'TM75 Draining Kiss',
    'Tm Air Cutter'             : 'TM76 Air Cutter',
    'Tm Air Slash'              : 'TM77 Air Slash',
    'Tm Stored Power'           : 'TM78 Stored Power',
    'Tm Avalanche'              : 'TM79 Avalanche',
    'Tm Volt Switch'            : 'TM80 Volt Switch',
    'Tm Fling'                  : 'TM81 Fling',
    'Tm Iron Head'              : 'TM82 Iron Head',
    'Tm Zen Headbutt'           : 'TM83 Zen Headbutt',
    'Tm Shadow Claw'            : 'TM84 Shadow Claw',
    'Tm Foul Play'              : 'TM85 Foul Play',
    'Tm Body Slam'              : 'TM86 Body Slam',
    'Tm Sleep Talk'             : 'TM87 Sleep Talk',
    'Tm Lash Out'               : 'TM88 Lash Out',
    'Tm Hyper Voice'            : 'TM89 Hyper Voice',
    'Tm Seed Bomb'              : 'TM90 Seed Bomb',
    'Tm Drain Punch'            : 'TM91 Drain Punch',
    'Tm Dazzling Gleam'         : 'TM92 Dazzling Gleam',
    'Tm Play Rough'             : 'TM93 Play Rough',
    'Tm Poison Jab'             : 'TM94 Poison Jab',
    'Tm Thunder Wave'           : 'TM95 Thunder Wave',
    'Tm Rock Slide'             : 'TM96 Rock Slide',
    'Tm Swords Dance'           : 'TM97 Swords Dance',
    'Tm U Turn'                 : 'TM98 U-turn',
    'Tm Flash Cannon'           : 'TM99 Flash Cannon',
    'Tm Dark Pulse'             : 'TM100 Dark Pulse',
}

SPECIFIC_ITEM_CASES = {
    'Pp Up'         : 'PP Up',
    'Pp Max'        : 'PP Max'
}

# Functions
def format_type(type: str) -> str:
    return type.replace('TYPE_', '').replace('_', '').title()

def format_sprite(sprite: str) -> str:    
    new = ''
    for i, c in enumerate(sprite):
        if i == 0:
            new += c.lower()
            continue
        
        if c == c.upper():
            new += f'-{c.lower()}'
        else:
            new += c
        
    if new in SPRITE_SPECIAL_CASES:
        return SPRITE_SPECIAL_CASES[new]
    
    return new

Learnset = list[str | dict[str]]
def get_learnset(learnset_data: list, learnset: str) -> Learnset | tuple[Learnset, Learnset]:
    entry = re.findall(learnset + r'\[\] = \{.+?\};', '\n'.join(learnset_data), re.S)
    
    entry: str = entry[0]
    
    new_learnset = []
    secondary_new_learnset = []
    for line in entry.split('\n\n'):
        line: str = line.strip()
        
        if 'MOVE_' in line and line != 'MOVE_UNAVAILABLE,':
            if 'level' in learnset.lower():
                temp = line.replace('LEVEL_UP_MOVE(', '').replace('),', '').strip().split(', ')
                
                current_level = int(temp[0])
                current_move = temp[1]
            else:
                current_move = line[:-1]
            
            if current_move == 'MOVE_FAINT_ATTACK':
                current_move = 'MOVE_FEINT_ATTACK'
            if current_move == 'MOVE_VICE_GRIP':
                current_move = 'MOVE_VISE_GRIP'
            
            if 'level' in learnset.lower():
                new_learnset.append({
                    'level'     : current_level,
                    'move'      : current_move,
                })
    
            elif 'teachable' in learnset.lower():
                if current_move in ALL_TMHMS:
                    new_learnset.append(current_move)
                else:
                    secondary_new_learnset.append(current_move)
            elif 'egg' in learnset.lower():
                new_learnset.append(current_move)
    
    if 'teachable' in learnset.lower():
        if secondary_new_learnset:
            return new_learnset, secondary_new_learnset
        else:
            return new_learnset, []
    
    return new_learnset

def build_stat_effect(effect: str) -> str:
    stat = STAT_MAPPING.get(effect.replace('MOVE_EFFECT_', '')[:3], None)
    if not stat:
        stat = STAT_MAPPING.get(effect.replace('MOVE_EFFECT_', '')[:6])
    stages = effect[-1]
    plurality = 'Stage' if stages == '1' else 'Stages'
    direction = 'Drop' if 'MINUS' in effect else 'Raise'
    return f'{direction} {stat} {stages} {plurality}'


def get_parent_name(raw_name: str, subname: str) -> str:
    new = ''
    for i, c in enumerate(subname):
        if c.isnumeric() or c == '_':
            new += c
            continue
        
        if c == c.upper():
            if subname[i - 1].isnumeric():
                new += c
            else:
                new += f'_{c}'
        else:
            new += c.upper()
    
    if not new.startswith('_'):
        new = f'_{new}'
        
    return raw_name.replace(new, '')
